name: Node.js CI

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run verify:fast
    # basic functional testing
    # https://github.com/modelcontextprotocol/inspector?tab=readme-ov-file#cli-mode
    - name: List tools
      run: npx @modelcontextprotocol/inspector --cli node dist/index.js --method tools/list
    - name: Call tool geocode
      run: npx @modelcontextprotocol/inspector --cli node dist/index.js --method tools/call --tool-name geocode --tool-arg text=vincennes
